// Page Documentation - Détection de Contenu IA
// Explication du système de détection de contenu généré par intelligence artificielle

import React from 'react';
import Link from 'next/link';
import Layout from '@/components/Layout';
import SEO from '@/components/SEO';
import { useLanguage } from '@/contexts/LanguageContext';

/**
 * Page de documentation sur la détection de contenu IA
 */
export default function AIDetectionPage() {
  const { locale } = useLanguage();
  const isFrench = locale === 'fr';

  return (
    <Layout>
      <SEO 
        title={isFrench ? "Détection de Contenu IA - OpenProvena" : "AI Content Detection - OpenProvena"}
        description={isFrench 
          ? "Découvrez comment OpenProvena détecte le contenu généré par intelligence artificielle."
          : "Learn how OpenProvena detects AI-generated content."
        }
      />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-b from-primary-50 to-white py-16">
        <div className="container-main">
          <div className="max-w-3xl mx-auto text-center">
            {/* Breadcrumb */}
            <nav className="mb-6 text-sm">
              <ol className="flex items-center justify-center gap-2 text-secondary-500">
                <li><Link href="/" className="hover:text-primary-600">{isFrench ? "Accueil" : "Home"}</Link></li>
                <li>/</li>
                <li><Link href="/docs" className="hover:text-primary-600">{isFrench ? "Documentation" : "Documentation"}</Link></li>
                <li>/</li>
                <li className="text-secondary-900">{isFrench ? "Détection IA" : "AI Detection"}</li>
              </ol>
            </nav>
            
            <h1 className="text-4xl md:text-5xl font-bold text-secondary-900 mb-6">
              {isFrench ? "Détection de Contenu IA" : "AI Content Detection"}
            </h1>
            <p className="text-xl text-secondary-600">
              {isFrench 
                ? "Découvrez comment notre système identifie le contenu généré par intelligence artificielle"
                : "Discover how our system identifies AI-generated content"
              }
            </p>
          </div>
        </div>
      </section>

      {/* Contenu principal */}
      <section className="py-16 bg-white">
        <div className="container-main">
          <div className="max-w-4xl mx-auto">
            
            {/* Introduction */}
            <div className="mb-12">
              <h2 className="text-2xl font-bold text-secondary-900 mb-4">
                {isFrench ? "Comment ça marche ?" : "How It Works"}
              </h2>
              <p className="text-secondary-600 leading-relaxed">
                {isFrench 
                  ? "Notre système de détection de contenu IA utilise des techniques avancées d'analyse statistique et de traitement du langage naturel (NLP) pour identifier les patterns caractéristiques du contenu généré par des modèles de langage comme GPT, Claude, ou Gemini."
                  : "Our AI content detection system uses advanced statistical analysis and natural language processing (NLP) techniques to identify patterns characteristic of content generated by language models like GPT, Claude, or Gemini."
                }
              </p>
            </div>

            {/* Méthodes de détection */}
            <div className="mb-12">
              <h2 className="text-2xl font-bold text-secondary-900 mb-6">
                {isFrench ? "Méthodes de détection" : "Detection Methods"}
              </h2>
              <div className="grid md:grid-cols-2 gap-6">
                {/* Méthode 1 */}
                <div className="bg-secondary-50 rounded-xl p-6">
                  <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-semibold text-secondary-900 mb-2">
                    {isFrench ? "Analyse de perplexité" : "Perplexity Analysis"}
                  </h3>
                  <p className="text-secondary-600 text-sm">
                    {isFrench 
                      ? "Mesure la prévisibilité du texte. Un contenu IA tend à avoir une perplexité plus uniforme."
                      : "Measures text predictability. AI content tends to have more uniform perplexity."
                    }
                  </p>
                </div>

                {/* Méthode 2 */}
                <div className="bg-secondary-50 rounded-xl p-6">
                  <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-semibold text-secondary-900 mb-2">
                    {isFrench ? "Détection de patterns" : "Pattern Detection"}
                  </h3>
                  <p className="text-secondary-600 text-sm">
                    {isFrench 
                      ? "Identifie les patterns répétitifs et les structures typiques du texte généré par IA."
                      : "Identifies repetitive patterns and structures typical of AI-generated text."
                    }
                  </p>
                </div>

                {/* Méthode 3 */}
                <div className="bg-secondary-50 rounded-xl p-6">
                  <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-semibold text-secondary-900 mb-2">
                    {isFrench ? "Analyse stylométrique" : "Stylometric Analysis"}
                  </h3>
                  <p className="text-secondary-600 text-sm">
                    {isFrench 
                      ? "Examine les caractéristiques stylistiques comme la longueur des phrases et le vocabulaire."
                      : "Examines stylistic characteristics like sentence length and vocabulary."
                    }
                  </p>
                </div>

                {/* Méthode 4 */}
                <div className="bg-secondary-50 rounded-xl p-6">
                  <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-semibold text-secondary-900 mb-2">
                    {isFrench ? "Réseau neuronal" : "Neural Network"}
                  </h3>
                  <p className="text-secondary-600 text-sm">
                    {isFrench 
                      ? "Modèle de deep learning entraîné sur des millions d'échantillons humains et IA."
                      : "Deep learning model trained on millions of human and AI samples."
                    }
                  </p>
                </div>
              </div>
            </div>

            {/* Interprétation des résultats */}
            <div className="mb-12">
              <h2 className="text-2xl font-bold text-secondary-900 mb-6">
                {isFrench ? "Interprétation des résultats" : "Interpreting Results"}
              </h2>
              
              <div className="space-y-4">
                {/* Très probable IA */}
                <div className="flex items-start gap-4 p-4 bg-red-50 rounded-lg border border-red-200">
                  <div className="w-3 h-3 rounded-full bg-red-500 mt-2 flex-shrink-0"></div>
                  <div>
                    <h4 className="font-semibold text-secondary-900">
                      {isFrench ? "Très probable IA (> 80%)" : "Highly Likely AI (> 80%)"}
                    </h4>
                    <p className="text-sm text-secondary-600">
                      {isFrench 
                        ? "Le contenu présente de fortes caractéristiques de génération par IA."
                        : "The content shows strong characteristics of AI generation."
                      }
                    </p>
                  </div>
                </div>

                {/* Probablement IA */}
                <div className="flex items-start gap-4 p-4 bg-orange-50 rounded-lg border border-orange-200">
                  <div className="w-3 h-3 rounded-full bg-orange-500 mt-2 flex-shrink-0"></div>
                  <div>
                    <h4 className="font-semibold text-secondary-900">
                      {isFrench ? "Probablement IA (60-80%)" : "Probably AI (60-80%)"}
                    </h4>
                    <p className="text-sm text-secondary-600">
                      {isFrench 
                        ? "Plusieurs indices suggèrent une origine IA."
                        : "Several indicators suggest an AI origin."
                      }
                    </p>
                  </div>
                </div>

                {/* Incertain */}
                <div className="flex items-start gap-4 p-4 bg-yellow-50 rounded-lg border border-yellow-200">
                  <div className="w-3 h-3 rounded-full bg-yellow-500 mt-2 flex-shrink-0"></div>
                  <div>
                    <h4 className="font-semibold text-secondary-900">
                      {isFrench ? "Incertain (40-60%)" : "Uncertain (40-60%)"}
                    </h4>
                    <p className="text-sm text-secondary-600">
                      {isFrench 
                        ? "Résultats mixtes, le contenu pourrait être hybride ou edited."
                        : "Mixed results, the content could be hybrid or edited."
                      }
                    </p>
                  </div>
                </div>

                {/* Probablement humain */}
                <div className="flex items-start gap-4 p-4 bg-lime-50 rounded-lg border border-lime-200">
                  <div className="w-3 h-3 rounded-full bg-lime-500 mt-2 flex-shrink-0"></div>
                  <div>
                    <h4 className="font-semibold text-secondary-900">
                      {isFrench ? "Probablement humain (20-40%)" : "Probably Human (20-40%)"}
                    </h4>
                    <p className="text-sm text-secondary-600">
                      {isFrench 
                        ? "Le contenu semble principalement humain."
                        : "The content appears primarily human."
                      }
                    </p>
                  </div>
                </div>

                {/* Très probable humain */}
                <div className="flex items-start gap-4 p-4 bg-emerald-50 rounded-lg border border-emerald-200">
                  <div className="w-3 h-3 rounded-full bg-emerald-500 mt-2 flex-shrink-0"></div>
                  <div>
                    <h4 className="font-semibold text-secondary-900">
                      {isFrench ? "Très probable humain (< 20%)" : "Highly Likely Human (< 20%)"}
                    </h4>
                    <p className="text-sm text-secondary-600">
                      {isFrench 
                        ? "Le contenu présente des caractéristiques typiquement humaines."
                        : "The content shows typically human characteristics."
                      }
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Limitations */}
            <div className="mb-12">
              <h2 className="text-2xl font-bold text-secondary-900 mb-4">
                {isFrench ? "Limitations" : "Limitations"}
              </h2>
              <div className="bg-secondary-50 rounded-xl p-6">
                <ul className="space-y-3 text-secondary-600">
                  <li className="flex items-start gap-3">
                    <svg className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span>
                      {isFrench 
                        ? "Le contenu humanisé (post-éditions, paraphrasage) peut échapper à la détection."
                        : "Humanized content (post-editing, paraphrasing) may escape detection."
                      }
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <svg className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span>
                      {isFrench 
                        ? "Les modèles IA les plus récents peuvent produire un texte plus naturel."
                        : "The latest AI models can produce more natural text."
                      }
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <svg className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span>
                      {isFrench 
                        ? "La détection n'est pas infaillible. Utilisez-la comme un indice parmi d'autres."
                        : "Detection is not infallible. Use it as one indicator among others."
                      }
                    </span>
                  </li>
                </ul>
              </div>
            </div>

            {/* CTA */}
            <div className="text-center">
              <h2 className="text-2xl font-bold text-secondary-900 mb-4">
                {isFrench ? "Essayez maintenant" : "Try it now"}
              </h2>
              <p className="text-secondary-600 mb-6">
                {isFrench 
                  ? "Analysez n'importe quel site pour connaître son score de confiance."
                  : "Analyze any website to find out its trust score."
                }
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <Link 
                  href="/search" 
                  className="px-6 py-3 bg-primary-600 text-white font-semibold rounded-xl hover:bg-primary-700 transition-colors"
                >
                  {isFrench ? "Analyser un site" : "Analyze a site"}
                </Link>
                <Link 
                  href="/" 
                  className="px-6 py-3 bg-secondary-100 text-secondary-700 font-semibold rounded-xl hover:bg-secondary-200 transition-colors"
                >
                  {isFrench ? "Retour à l'accueil" : "Back to home"}
                </Link>
              </div>
            </div>

          </div>
        </div>
      </section>
    </Layout>
  );
}
